#!/usr/bin/env python

# Copyright (C) 2012, 2013 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import sys
import pkg.libs.variables as variables
import pkg.libs.common as common
import pkg.libs.copy as copy

from subprocess import call, check_output

# Get the arguments
arguments = sys.argv[1:]

min_choices = 0
max_choices = 3

# If there is only one parameter and it's not equal to ZFS related stuff,
# and there are no modules listed in pkg/hooks/addon.sh, then let the user
# do a direct initramfs creation. If we do have modules listed, then let the
# user know we need two parameters.
if len(arguments) == 1:
	if arguments[0] != "1" and arguments[0] != "6":
		if not common.addon.addon_mods:
			common.choice = arguments[0]
		else:
			common.die("You must pass a kernel parameter")

# If not equal to exactly two parameters, we will just ignore all the arguments
elif len(arguments) == 2:
	common.choice = arguments[0]
	common.kernel = arguments[1]

user = check_output(["whoami"], universal_newlines=True).strip()

if user != "root":
	common.die("This program must be ran as root")

###############################################
# The main entry point starts here
###############################################

call(["clear"])

common.print_header()
common.print_menu()

# If we have any modules to copy, then get the kernel modules directory
# for these modules.
if common.addon.addon_mods:
	common.do_kernel()

common.get_arch()
common.print_start()
common.clean()
common.check_prelim_binaries()

# Bring some variables over from the common namespace to the copy namespace
copy.kernel = common.kernel
copy.modules = common.modules
copy.lmodules = common.lmodules

copy.check_binaries()
copy.install()
copy.copy_modules()
common.create_links()
copy.copy_deps()
common.last_steps()
common.create()
common.clean_exit()
