#!/usr/bin/env python

# Copyright (C) 2012, 2013 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import sys
import pkg.libs.variables as variables
import pkg.libs.common as common
import pkg.libs.copy as copy

from subprocess import call, check_output

# Get the arguments
arguments = sys.argv[1:]

min_choices = 0
max_choices = 3

# If not equal to exactly two parameters, we will just ignore all the arguments
if len(arguments) == 2:
	common.choice = arguments[0]
	common.kernel = arguments[1]

user = check_output(["whoami"], universal_newlines=True).strip()

if user != "root":
	die("This program must be ran as root")

###############################################
# The main entry point starts here
###############################################

call(["clear"])

common.print_header()
common.print_menu()
common.do_kernel()
common.get_arch()
common.print_start()
common.clean()
common.create_dirs()
common.check_prelim_binaries()

# Bring some variables over from the common namespace to the copy namespace
copy.kernel = common.kernel
copy.lmodules = common.lmodules

copy.check_binaries()
copy.copy_binaries()
copy.get_modules()
copy.copy_modules()
copy.copy_docs()
copy.copy_udev()
copy.copy_other()
copy.do_deps()

common.create_links()
common.config_files()
common.create()
common.clean_exit()
