#!/bin/bash

# ZFS InitramFS Creator
# This script will generate the entire ZFS initramfs with
# all of it's dependencies.

# Copyright (C) 2012 Jonathan Vasquez
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License v2 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
	
# Version 1.0.0

KERNEL_NAME="3.3.0-LAPTOP"
MOD_PATH="/lib/modules/${KERNEL_NAME}"
TMPDIR="tempinit"

mkdir ${TMPDIR} 
cd ${TMPDIR}

mkdir -p bin sbin proc sys dev etc lib lib64 mnt/root lib/modules/${KERNEL_NAME}

# Copy Requires Files
BINS="busybox zpool_layout hostid"

for B in ${BINS} ; do
#	echo "Adding ${SPL} into initramfs"
	if [ "${B}" == "hostid" ] ; then
		cp /usr/bin/${B} bin
	else
		cp /bin/${B} bin
	fi
done

# Copy SPL Files
SPL_BINARIES="spl splat"

for SPL in ${SPL_BINARIES} ; do
#	echo "Adding ${SPL} into initramfs"
	cp /sbin/${SPL} sbin
done

SPL_MODULES="spl splat"

for SPL in ${SPL_MODULES} ; do
	
#	echo "Adding ${SPL} into initramfs"
	cp /lib/modules/${KERNEL_NAME}/addon/spl/${SPL}/${SPL}.ko lib/modules/${KERNEL_NAME}
done

# Copy ZFS Files
ZFS_BINARIES="mount.zfs zdb zfs zinject zpios zpool ztest"

for ZFS in ${ZFS_BINARIES} ; do
#	echo "Adding ${ZFS} into initramfs"
	cp /sbin/${ZFS} sbin
done

ZFS_MODULES="zavl znvpair zunicode zcommon zfs zpios"

for ZFS in ${ZFS_MODULES} ; do
#	echo "Adding ${ZFS} into initramfs"
	if [ "${ZFS}" == "zavl" ] ; then
		cp /lib/modules/${KERNEL_NAME}/addon/zfs/avl/${ZFS}.ko lib/modules/${KERNEL_NAME}
	elif [ "${ZFS}" == "znvpair" ] ; then
		cp /lib/modules/${KERNEL_NAME}/addon/zfs/nvpair/${ZFS}.ko lib/modules/${KERNEL_NAME}
	elif [ "${ZFS}" == "zunicode" ] ; then
		cp /lib/modules/${KERNEL_NAME}/addon/zfs/unicode/${ZFS}.ko lib/modules/${KERNEL_NAME}
	else 	
		cp /lib/modules/${KERNEL_NAME}/addon/zfs/${ZFS}/${ZFS}.ko lib/modules/${KERNEL_NAME}
	fi 
done

# Get and copy all dependencies
ALL_BINARIES="${SPL_BINARIES} ${ZFS_BINARIES} ${BINS}"

for X in ${ALL_BINARIES} ; do
	if [ "${X}" == "busybox" ] || [ "${X}" == "zpool_layout" ] || [ "${X}" == "hostid" ] ; then
		DEPS="$(ldd bin/${X} | awk '/lib64/ {print $1}' | sed "s/\/lib64\///")"
	else
		DEPS="$(ldd sbin/${X} | awk '/lib64/ {print $1}' | sed "s/\/lib64\///")"
	fi 

	for Y in ${DEPS} ; do
		cp -Lf /lib64/${Y} lib64
	done
done

# Create Symlinks
BUSYBOX_TARGETS="mount tty sh"

cd bin/

for BB in ${BUSYBOX_TARGETS}; do
	ln -s busybox ${BB}
done

cd ..

# Create Additional Files
touch etc/mtab

# Copy the init script
cp ../init .

# Pack & Compress the files into an initramfs.

find . -print0 | cpio -o --null --format=newc | gzip -9 > ../ZFS-${KERNEL_NAME}.img

# Clean up
rm -rf ../${TMPDIR}

echo "Complete :)"

echo "Please copy the ZFS-${KERNEL_NAME}.img to your /boot directory"