#!/usr/bin/python3

"""
Copyright 2012-2014 Jonathan Vasquez <jvasquez1011@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at:

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import sys
import os

from subprocess import call

from pkg.libs.variables import Variables
from pkg.libs.core import Core
from pkg.libs.copy import Copy
from pkg.libs.toolkit import Toolkit

tools = Toolkit()
var = Variables()

class Creator(object):
	def __init__(self):
		self.core = Core()
		self.copy = Copy(self.core)

	def main(self):
		"""
		Let the games begin!
		"""

		tools.welcome(self.core)

		call(["clear"])

		self.core.print_header()
		self.core.print_menu()
		
		if self.core.addon.modules:
			self.core.do_kernel()

		self.core.get_arch()
		tools.print_start()
		tools.clean()
		self.core.check_prelim_binaries()
		self.core.create_baselayout()
		self.copy.check_binaries()
		self.copy.install()
		self.copy.copy_modules()
		self.core.create_links()
		self.copy.copy_deps()
		self.core.last_steps()
		self.core.create()
		tools.clean_exit(self.core.get_initrd())

if __name__ == '__main__':
	init = Creator()
	init.main()
