#!/usr/bin/env python

"""
Copyright (C) 2012-2014 Jonathan Vasquez <fearedbliss@funtoo.org>

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
"""

import sys
import os

from subprocess import call

from pkg.libs.variables import Variables
from pkg.libs.core import Core
from pkg.libs.copy import Copy
from pkg.libs.toolkit import Toolkit

class Creator(object):
	def __init__(self):
		self.var = Variables()
		self.tools = Toolkit(self.var)
		self.core = Core(self.var, self.tools)
		self.copy = Copy(self.core, self.var, self.tools)

	def main(self):
		"""
		Let the games begin!
		"""

		self.tools.welcome(self.core)

		#call(["clear"])

		self.core.print_header()
		self.core.print_menu()
		
		if self.core.addon.modules:
			self.core.do_kernel()

		self.core.get_arch()
		self.tools.print_start()
		self.tools.clean()
		self.core.check_prelim_binaries()
		self.core.create_baselayout()

		self.copy.check_binaries()
		"""
		copy.install()
		copy.copy_modules()
		common.create_links()
		copy.copy_deps()
		common.last_steps()
		common.create()
		common.clean_exit()
		"""

if __name__ == '__main__':
	init = Creator()
	init.main()
