#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez
#
# This source code is released under the MIT license which can be found
# in the LICENSE file.

# Variables
NEW_ROOT="/mnt/root"
NEW_INIT="/sbin/init"

# Function to start rescue shell
rescue_shell()
{
	echo "Booting into rescue shell..."
	busybox --install -s
	exec /bin/sh
}

# Mount Kernel Devices
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

# Prevent kernel from printing on screen
echo 0 > /proc/sys/kernel/printk

# Make LVM Volume Group/Pools available 
lvm vgchange -a y || rescue_shell
lvm vgscan --mknodes || rescue_shell

# Mount the root pool 
if [ -z "${pool_root}" ]; then
	echo "pool_root wasn't defined in the kernel parameters. Throwing you into rescue shell!" && rescue_shell
else
	if [ -z "${fstype}" ] && [ -z "${options}" ]; then
		mount ${pool_root} ${NEW_ROOT} || rescue_shell
	elif [ -z "${fstype}" ]; then
		mount -o ${options} ${pool_root} ${NEW_ROOT} || rescue_shell
	elif [ -z "${options}" ]; then
		mount -t ${fstype} ${pool_root} ${NEW_ROOT} || rescue_shell	
	else
		mount -t ${fstype} -o ${options} ${pool_root} ${NEW_ROOT} || rescue_shell
	fi
fi

# Unmount Kernel Devices
umount /proc
umount /dev
umount /sys

# Switch to the new root
exec switch_root ${NEW_ROOT} ${NEW_INIT} || rescue_shell
