#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ZFS_POOL_NAME=""
JV_MOD_PATH=""

# Function to start rescue shell
rescue_shell() {
	echo "Booting into rescue shell"
	busybox --install -s
	exec /bin/sh
}

# Function to load ZFS modules 
load_modules() {
	MODULES="spl splat zavl znvpair zcommon zunicode zfs zpios"
	
	for MODULE in ${MODULES}; do
		insmod ${JV_MOD_PATH}/${MODULE}.ko
	done
}

# Mount Kernel Devices 
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

# Wait a little for trailing kernel messages
sleep 2 

# Load ZFS Modules
load_modules || rescue_shell

# Mount ZFS Pool
zpool import -f -d /dev -o cachefile= -R /mnt/root ${ZFS_POOL_NAME} || rescue_shell

# Unmount Kernel Devices
umount /proc
umount /dev
umount /sys

# Switch to the new root
exec switch_root /mnt/root /sbin/init || rescue_shell
