#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez
#
# This source code is released under the MIT license which can be found
# in the LICENSE file.

# Variables
NEW_ROOT="/mnt/root"
NEW_INIT="/sbin/init"

# Function to start rescue shell
rescue_shell()
{
	echo "Booting into rescue shell..."
	busybox --install -s
	exec /bin/sh
}

# Function to load ZFS modules
load_modules()
{
	modules="spl splat zavl znvpair zcommon zunicode zfs zpios"

	for x in ${modules}; do
		# If it's the ZFS module, and there is a cachesize set, then set the arc max to it
		if [ "${x}" = "zfs" -a ! -z "${cache_size}" ]; then
			modprobe ${x} zfs_arc_max=${cache_size}
		else
			modprobe ${x}
		fi
	done
}

# Mount Kernel Devices
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

# Prevent kernel from printing on screen
echo 0 > /proc/sys/kernel/printk

# Load ZFS Modules
load_modules || rescue_shell

# Mount ZFS Pool
zpool import -f -d /dev -o cachefile= -R ${NEW_ROOT} ${pool_name} || rescue_shell

# Unmount Kernel Devices
umount /proc
umount /dev
umount /sys

# Switch to the new root
exec switch_root ${NEW_ROOT} ${NEW_INIT} || rescue_shell
