#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez
#
# This source code is released under the MIT license which can be found
# in the LICENSE file.

# Variables
NEW_ROOT="/mnt/root"
NEW_INIT="/sbin/init"

# Function to start rescue shell
rescue_shell()
{
	echo "Booting into rescue shell..."
	busybox --install -s
	exec /bin/sh
}

# Mount Kernel Devices
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

# Prevent kernel from printing on screen
echo 0 > /proc/sys/kernel/printk

# Scan for raid arrays and save them in mdadm.conf
mdadm --examine --scan > /etc/mdadm.conf

# Assemble all raid devices
mdadm --assemble --scan

# Mount the root node

if [ -z "${root_node}" ]; then
	echo "root_node wasn't defined in the root parameters. Throwing you into rescue shell!" && rescue_shell
else
	if [ -z "${fstype}" -a -z "${options}" ]; then
		mount /dev/${root_node} ${NEW_ROOT} || rescue_shell
	elif [ -z "${fstype}" ]; then
		mount -o ${options} /dev/${root_node} ${NEW_ROOT} || rescue_shell
	elif [ -z "${options}" ]; then
		mount -t ${fstype} /dev/${root_node} ${NEW_ROOT} || rescue_shell	
	else
		mount -t ${fstype} -o ${options} /dev/${root_node} ${NEW_ROOT} || rescue_shell
	fi
fi

# Unmount Kernel Devices
umount /proc
umount /dev
umount /sys

# Switch to the new root
exec switch_root ${NEW_ROOT} ${NEW_INIT} || rescue_shell
