#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Variables
NEW_ROOT="/mnt/root"
NEW_INIT="/sbin/init"

# Function to start rescue shell
rescue_shell() {
	echo "Booting into rescue shell"
	busybox --install -s
	exec /bin/sh
}

# Mount Kernel Devices 
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

echo "Variables:"
echo "Pool Name: ${pool_name}"
echo "Pool Root: ${pool_root}"
echo "Root FS Type: ${rootfstype}"

# Wait a little for trailing kernel messages
sleep 2 

# Mount LVM Pool
lvm vgchange -a y ${pool_name} || rescue_shell
lvm vgscan --mknodes || rescue_shell

mount -t ${options} ${rootfstype} /dev/${pool_name}/${pool_root} ${NEW_ROOT} || rescue_shell

# Unmount Kernel Devices
umount /proc
umount /dev
umount /sys

# Switch to the new root
exec switch_root ${NEW_ROOT} ${NEW_INIT} || rescue_shell
