#!/bin/busybox sh

# Copyright (C) 2012, 2013 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This Source Code Form is "Incompatible With Secondary Licenses", as
# defined by the Mozilla Public License, v. 2.0.

# Import Functions
. $(pwd)/resources/generic.sh

# Variables
NEW_ROOT="/mnt/root"
INIT="/sbin/init"

USE_ZFS="0"
USE_LUKS="0"

### Lasu la ludoj komenci ###

welcome

einfo "Mounting kernel devices..."
mnt_kernel_devs || die "Failed to mount kernel devices"

einfo "Parsing command line values..."
parse_cmdline

prevent_printk

einfo "Loading modules..."
load_modules || die "Failed to load kernel modules"

if [ "${recover}" = "1" ]; then
	ewarn "Recovery Mode Enabled... Entering Rescue Environment"
	rescue_shell
fi

if [ "${USE_LUKS}" = "1" ]; then
        luks_trigger
fi

if [ "${USE_ZFS}" = "1" ]; then
        zfs_trigger
fi

if [ "${USE_NORMAL}" = "1" ]; then
	normal_trigger
fi

einfo "Unmounting kernel devices..."
umnt_kernel_devs || die "Failed to umount kernel devices"

einfo "Switching to your rootfs..." && eline
switch_to_new_root
