#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez
#
# This source code is released under the MIT license which can be found
# in the LICENSE file.

# Variables
NEW_ROOT="/mnt/root"
NEW_INIT="/sbin/init"

# Function to start rescue shell
rescue_shell()
{
	echo "Booting into rescue shell..."
	busybox --install -s
	exec /bin/sh
}

# Mount Kernel Devices
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

# Prevent kernel from printing on screen
echo 0 > /proc/sys/kernel/printk

# Assemble all raid devices
mdadm --assemble --scan

# Mount LVM Pool
lvm vgchange -a y ${pool_name} || rescue_shell
lvm vgscan --mknodes || rescue_shell

mount -t ${fstype} -o ${options} /dev/${pool_name}/${pool_root} ${NEW_ROOT} || rescue_shell

# Unmount Kernel Devices
umount /proc
umount /dev
umount /sys

# Switch to the new root
exec switch_root ${NEW_ROOT} ${NEW_INIT} || rescue_shell
