#!/bin/busybox sh

# Copyright (C) 2012 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Import Functions
. $(pwd)/resources/generic.sh

# Variables
NEW_ROOT="/mnt/root"
NEW_INIT="/sbin/init"

USE_ZFS="0"
USE_LUKS="0"

#################### Let the games begin ####################

welcome

einfo "Mounting kernel devices..."
mnt_kernel_devs || die "Failed to mount kernel devices"

prevent_printk

einfo "Loading modules..."
load_modules || die "Failed to load kernel modules"

luks_trigger
zfs_trigger

einfo "Unmounting kernel devices..."
umnt_kernel_devs || die "Failed to umount kernel devices"

einfo "Switching to your rootfs..." && eline
switch_to_new_root
